# -*- coding: utf-8 -*-
"""Exemplo Correlação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_5rV34sjMo1jhZ_ph_XFKryKPPeRtwJ
"""

import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score

Receita = np.array([2, 15, 25, 35, 45, 55, 65, 75, 80, 85, 32, 62, 2, 15, 25, 35, 45, 55, 65, 75, 80, 85, 32, 62])
Preco = np.array([10, 20, 14, 32, 22, 38, 41, 52, 55, 61, 21, 44, 10, 20, 14, 32, 22, 38, 41, 52, 55, 61, 21, 44])

plt.scatter(Receita, Preco, color="Black")
plt.show()

Receita = np.array([2, 15, 25, 35, 45, 55, 65, 75, 80, 85, 32, 62, 2, 15, 25, 35, 45, 55, 65, 75, 80, 85, 32, 62])
Preco = np.array([10, 20, 14, 32, 22, 38, 41, 52, 55, 61, 21, 44, 10, 20, 14, 32, 22, 38, 41, 52, 55, 61, 21, 44])

regr = linear_model.LinearRegression()
regr.fit(Receita.reshape(-1,1), Preco)
y = regr.predict(Receita.reshape(-1,1))

print('Coefficients: /n', regr.coef_)
print('Intercept: /n', regr.intercept_)

plt.scatter(Receita, Preco, color='black')
plt.plot(Receita, y, color='blue', linewidth=3)